### ISSUE TITLE
Unable to run the examples 

### ISSUE THREAD

**Issue by ghost** [jamieowen/threeflow.js#6]
Hi i tried to follow your instructions in the readme, and installed threeflow globally , but when I try to type "threeflow init"  I always get this error 
![capture](https://cloud.githubusercontent.com/assets/9971059/9560583/d0462d7e-4e4e-11e5-97f9-b5e9b7601908.PNG)

I am quite new to this. i would appreciate if you could point out where I am going wrong

**Comment by jamieowen** [comment]
Hey, 
This looks like a Windows related issue.  And likely to do with path naming..
I haven't got time to look in to this and no access to a windows machine at the moment.  Sorry about that. :(

How's your node.js skills?

**Comment by ghost** [comment]
Ahh I see, I will look out for the path naming issue at my end. I have just started out with Nodejs. I am trying to see if I can get threeflow to run on a server. It looks really nifty btw :+1:

**Comment by jamieowen** [comment]
Cool, thanks!

If you notice in your screenshot, one of the paths has a double \  .e.g - ..Roaming\npm\node_modules
Not sure if this is part of the problem but I have heard paths can be tricky cross platform especially with global node modules. Which is what the threeflow command line stuff is doing.

The source code for the command line tool is pretty is pretty simple and is found in the 
src/server/threeflow.bin.coffee file.

If you do want to run it on a server, you could also run it directly from the source code from within your own node app using the src/server/server.coffee code. ( rather than using the 'threeflow init' command line stuff )

**Comment by ghost** [comment]
I think you are right.I tried installing it on c9.io and threeflow worked there without a hitch. Will do as you suggested. Thank you for taking the time to answer my queries!!
